# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: RUN Smoke Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the testing environment
        default: staging
        options:
        - production
        - staging
  schedule:
  - cron: "0 6 * * 1-5"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PASS_1: "${{ secrets.PASS_1 }}"
      PASS_2: "${{ secrets.PASS_2 }}"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Manual RUN of Tests
      if: github.event_name == 'workflow_dispatch'
      run: |
        pytest -v -s --env ${{ github.event.inputs.environment }}
    - name: Scheduled RUN of Tests
      if: github.event_name == 'schedule'
      run: |
        pytest -v -s --env staging
