# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: RUN All Smoke Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the testing environment
        required: true
        default: staging
        options:
        - production
        - staging
  schedule:
    - cron:  "00 6 * * *"
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: RUN Tests
      run: |
        pytest -v -s
